# name: Playwright Tests

# on:
#   push:
#     branches: main
#   pull_request:
#     branches: main

# jobs:
#   test:
#     env:
#       DATABASE_URL: postgresql://postgres:postgres@postgres:5432/db
#       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#     runs-on: ubuntu-latest
#     services:
#       postgres:
#         image: postgres
#         env:
#           POSTGRES_DB: db
#           POSTGRES_USER: postgres
#           POSTGRES_PASSWORD: postgres
#         options: >-
#           --health-cmd pg_isready
#           --health-interval 10s
#           --health-timeout 5s
#           --health-retries 5
#         ports:
#           - 5432:5432

#     container:
#       image: mcr.microsoft.com/playwright:v1.45.1-jammy

#     steps:
#       - uses: actions/checkout@v4
#       - uses: pnpm/action-setup@v3
#         with:
#           version: 8

#       - name: Set up Node
#         uses: actions/setup-node@v4
#         with:
#           node-version: lts/*
#           cache: 'pnpm'

#       - name: Install dependencies
#         run: pnpm install && pnpm install:playwright:deps

#       - name: Build application
#         run: pnpm build:ci

#       - name: Start application
#         run: pnpm start &

#       - name: Push database
#         run: pnpm push

#       - name: Run Playwright tests
#         run: pnpm test
#         env:
#           HOME: /root
#           TEST_EMAIL: ${{secrets.TEST_EMAIL}}
#           TEST_PASSWORD: ${{secrets.TEST_PASSWORD}}
#           GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
#           GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
#           NEXTAUTH_URL: ${{secrets.NEXTAUTH_URL}}
#           NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}

#       - uses: actions/upload-artifact@v4
#         if: always()
#         with:
#           name: playwright-report
#           path: playwright-report/
#           retention-days: 30